# version: '3.4'


version: '3.8'
services:
  # web.api:
  #   image: ${DOCKER_REGISTRY-}webapi
  #   build:
  #     context: .
  #     dockerfile: src/Web.API/Dockerfile
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CleanApp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    volumes:
      - C:\\GitHub\\CleanArchitecture\\src\\Web.API\\seq\\Logs:/data

volumes:
  postgres-data:
