name: Build dotNet Apps

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 24.x
    - name: Setup Dotnet 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Nuget packages
      run: dotnet restore CleanArchitecture.sln
    - name: Build Solution
      run: dotnet build /p:GenerateClient=false CleanArchitecture.sln -c Release --no-restore
    
